apiVersion: batch/v1
kind: CronJob
metadata:
  name: stores-client
  namespace: bobadojo
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: stores-client
            image: ghcr.io/bobadojo/stores-client:latest
            imagePullPolicy: IfNotPresent
            command:
            - /usr/local/bin/stores-client
            - -addr
            - stores.timbx.me:443
            - -api-key
            - $(key)
            envFrom:
            - secretRef:
                name: apikey
          restartPolicy: OnFailure
          nodeSelector:
            kubernetes.io/arch: arm64
